### PR TITLE
Notes on quiet rooms, local traffic warnings, religious holidays 

### PR DESCRIPTION
**Pull request by vsmart**
Three additions from experience of helping to organise ClojureBridge Berlin events. 

1. Line 34: (Quiet room accessibility)
We have had the feedback that our quiet room was too close to the stage, so there was no way to enter it without other people noticing (which may be uncomfortable for people). 

2.  Line 57: (Local traffic warnings) 
Make sure to check local traffic and weather warnings.
A big bike race through the city the day *after* our event meant all public transit was cancelled that day. This is something easily overlooked, but one should consider when picking a date. 

3. Line 58: (Religious/cultural holidays) 
It's easy to overlook holidays you don't celebrate. It's important to check a calendar that includes these to allow for a wide range of people to attend your event.

### CODE REVIEW

**Comment by erikr** [comment]
All great additions, thank you! Do you happen to know of any good calendars we could link to for the 3rd point?

**Comment by vsmart** [comment]
@erikr a quick search brought up http://www.interfaithcalendar.org/ , what do you think? It's not a great interface but it seems to be very inclusive.

**Comment by vsmart** [comment]
@erikr Added the link to the calendar!

**Comment by erikr** [comment]
Thank you, that looks good!
:shipit:

**Pull request merged**
