### PR TITLE
adding breastpump information

### PR DESCRIPTION
**Pull request by elliewix**
Adding an entry about the needs for nursing parents needing to pump breastmilk

### CODE REVIEW

**Comment by erikr** [comment]
Thanks for this great suggestion! I think we could make this a little bit more generic and include breastfeeding too - inspired by the relevant section of [PyCon UK](http://2016.pyconuk.org/diversity-accessibility-inclusion/).

My first idea would be:
```
Some attendees may need to breastfeed or pump breastmilk. The best is to have a space planned for attendees for this purpose, and include a statement about who to make space requests to. A nursing parent at a conference will likely need to nurse/pump 1-3 times between 08:00 and 18:00 in 30 minute blocks of time (between setup, pumping, and cleanup). At a minimum, the space just needs to be clean, private, and have electricity. Include access to a refrigerator or mini-fridge if that is an option. Most event spaces (or HR departments, if the event is in an office space) are used to handling these sort of inquries. Build in longer mid-morning/afternoon break times (30 minutes) if you are planning an event for women and may have many attendees who need nursing/pumping breaks. Also be explicit in that this is an optional service, and that feeding is allowed wherever and whenever the attendee likes, to avoid making it seem like this is only allowed in the private space.
```

Any thoughts?

**Comment by elliewix** [comment]
Those are good additions!  My only (small) concern is grouping nursing/pumping together. Not every event/space is designed for people to have kids around.  But never bad to include language that breastfeeding is (in the US) a right to do in public, so nursing parents comfortable doing it in a public space should be fully supported.

**Comment by erikr** [comment]
Good point. I'll add a separate item before this about children in general, to frame it a bit better. But it seemed to make sense to group them with their similar requirements (as far as I can determine).

**Comment by elliewix** [comment]
Oh ya, it certainly does.  When you speak about childcare as well you can include trying to get a private nursing area nearby.  Some nursing parents are fine nursing in public, but not every baby will nurse with noise and traffic around :-)

**Comment by erikr** [comment]
Thanks! I added this in https://github.com/erikr/lessobviouschecklist/commit/64d44208283086ac8c7982cf27724fbcee0d63a1 and https://github.com/erikr/lessobviouschecklist/commit/17ae347fa6902d6a0d82d7b6aee661acd4263fbf

**Pull request closed without merging**
