### PR TITLE
Add bathrooms for non-binary folk

### PR DESCRIPTION
**Pull request by me-and**
Two of three incoming pull requests: "Make non-binary people feel more at home with explicitly gender-neutral bathrooms. This may also be helpful for parents and for other trans people. The Eliot Center, used by Open Source Bridge, has some toilets that are explicitly gender-neutral, as well as signs making it clear their binary gendered bathrooms are trans-inclusive."

### CODE REVIEW

**Comment by erikr** [comment]
I like this personally, but I have also heard concerns raised, mainly by women, that would feel uncomfortable with entirely mixed bathrooms. To be clear, I'm reading your suggestion as "there is no gender distinction in which bathroom to use", and not as "transgender people are welcome to use the bathroom of the gender they identify as" - the latter is already mentioned.

I have heard the suggestion that this is not an issue when the different lockable cubicles include their own sink/mirror, but that setup is extremely rare in conference venues in my experience, at least in Europe.

Personally, I really don't care who I'm sharing my bathroom with, but I'm hesitant to do this without further input on the balance between making non-binary people feel more at home, and ensuring everyone feels comfortable in their bathroom. I'm not in either group, so I can't really form a good picture of this.

**Comment by me-and** [comment]
Ah, I think I was being unclear. In at least the general case I don't think there should be _no_ gendered bathrooms – all the reasons you mention are good reasons, and I believe there are also religious access requirements that are relevant too – but I think ideally both gendered and ungendered bathrooms would be provided.

How clarifying with something like "Make non-binary people feel more at home by providing explicitly gender-neutral bathrooms as well as gendered ones. …"?

**Comment by erikr** [comment]
Yes, I see what you mean. It's a good addition, but I'm wondering whether we can make a further recommendation on how this could work in practice. In conference venues where I've both attended and organised, there are generally two fairly large bathrooms available to attendees, one male and one female. That leaves nowhere to assign as an ungendered bathroom.

I can only think of two situations to make it work:
* If there is a separate wheelchair accessible toilet, assigned that as an ungendered bathroom available to everyone. They usually are already ungendered, in my experience. Most conferences I see myself do not have such a high ratio of wheelchair users that this would be a capacity issue.
* If the conference is on multiple floors, each with separate toilets, toilets on some floors could be assigned ungendered. This isn't very common though, in my experience.

Do you have any other ideas?

**Comment by me-and** [comment]
Both of those seem like sensible suggestions to me. The only tech conference I've been to was OSBridge, and the venue already had gender-neutral toilets anyway, so I've nothing from practical experience, I'm afraid.

**Comment by erikr** [comment]
Merged with some rewording, thanks!

I removed the explicit reference to the Eliot Center, because [Geek Feminism wiki](http://geekfeminism.wikia.com/wiki/Restroom) claims their signage had issues too.

**Comment by me-and** [comment]
Fair re removing the reference to the Eliot centre; I think their gender-neutral bathrooms were about as good as they could be, but the wording on the binary gendered ones wasn't great.

**Pull request closed without merging**
