### PR TITLE
Add a bit of wisdom learned from eurucamp

### PR DESCRIPTION
**Pull request by skade**
Hi, some tiny things we learned at eurucamp on top of this great list :)

### CODE REVIEW

**Comment by skade** [comment]
@erikr Ping :). Are there any issues with this PR I can amend?

**Comment by erikr** [comment]
Thanks for the PR. I've been incredibly busy, so I haven't had time to look at it yet. I will be able to within the next few weeks though. Thanks for your patience!

**Comment by skade** [comment]
👍 happy to see you active. Take your time :)

**Comment by erikr** [comment]
Thank you! Could you tell me which conference this was exactly, so that I can link to it in AUTHORS?

**Comment by skade** [comment]
The conference was eurucamp (eurucamp.org), later refined at RustFest (rustfest.eu).

**Pull request merged**
